name: ML Analytics

on:
  schedule:
    # Jalankan otomatis setiap 1 jam
    - cron: '0 * * * *'
  workflow_dispatch:  # Bisa juga dijalankan manual

jobs:
  run-analytics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install requests numpy scikit-learn
        
    - name: Run Anomaly Detection
      run: python ml/anomaly_detection.py
      
    - name: Run Prediction
      run: python ml/prediction.py